name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
env:
  BIN_1: giwifi
  BIN_2: giwifi-ui
jobs:
  build:
    continue-on-error: true
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: x86_64-windows-msvc
            runner: windows-latest
            target: x86_64-pc-windows-msvc

          - name: x86_64-windows-gnu
            runner: windows-latest
            target: x86_64-pc-windows-gnu

          - name: i686-windows-gnu
            runner: windows-latest
            target: i686-pc-windows-gnu

          - name: i686-windows-msvc
            runner: windows-latest
            target: i686-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Set up MinGW
        if: contains(matrix.target,'i686') && runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
          version: 12.2.0

      - uses: ilammy/setup-nasm@v1

      - if: runner.os == 'Linux' && !contains(matrix.target, 'aarch')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools libssl-dev gcc-multilib
              export CC=musl-gcc
              export OPENSSL_DIR=/usr/lib/x86_64-linux-gnu
              export PKG_CONFIG_ALLOW_CROSS=1
              export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

      - uses: Swatinem/rust-cache@v2
      - run: cd rust; cargo build --verbose --locked --release --target ${{ matrix.target }}; ls
      - run: ls rust/target/${{ matrix.target }}/release

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            rust/target/${{ matrix.target }}/release/${{ env.BIN_1 }}.exe
            rust/target/${{ matrix.target }}/release/${{ env.BIN_1 }}
            rust/target/${{ matrix.target }}/release/${{ env.BIN_2 }}.exe
            rust/target/${{ matrix.target }}/release/${{ env.BIN_2 }}
